In [2]:
import numpy as np
import pandas as pd
import arff
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from autofeat import AutoFeatRegressor 
import featuretools as ft

In [24]:
with open("german-credit-R.arff", "r") as file:
    data = arff.load(file)
df = pd.DataFrame(data["data"], columns=[attr[0] for attr in data["attributes"]])

In [25]:
cat_cols = ["Sex", "Housing", "Saving accounts", "Checking account", "Purpose","Risk"]
for col in cat_cols:
    df[col] = LabelEncoder().fit_transform(df[col])

In [37]:
df.isna().sum()

Age                 0
Sex                 0
Job                 0
Housing             0
Saving accounts     0
Checking account    0
Credit amount       0
Duration            0
Purpose             0
Risk                0
customer_id         0
dtype: int64

In [5]:
X = df.drop(columns=["Risk"])  
y = df["Risk"]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(f"Précision : {accuracy_score(y_test, y_pred):.2f}")
print(classification_report(y_test, y_pred))
print("Matrice de confusion :\n", confusion_matrix(y_test, y_pred))

Précision : 0.76
              precision    recall  f1-score   support

           0       0.65      0.37      0.47        59
           1       0.78      0.91      0.84       141

    accuracy                           0.76       200
   macro avg       0.71      0.64      0.66       200
weighted avg       0.74      0.76      0.73       200

Matrice de confusion :
 [[ 22  37]
 [ 12 129]]

In [12]:
#https://medium.com/@boukamchahamdi/autofeat-automating-feature-engineering-with-python-f22ec23265a9
af = AutoFeatRegressor( feateng_steps=2,n_jobs=-1)  

X_train_af = af.fit_transform(X_train, y_train)
X_test_af = af.transform(X_test)
X_train_af.head()
print(f"Nombre de nouvelles features créées : {X_train_af.shape[1] - X_train.shape[1]}")

model_af = LogisticRegression()
model_af.fit(X_train_af, y_train)
y_pred_af = model_af.predict(X_test_af)

print("\n Performance APRÈS AutoFeat")
print(f"Précision : {accuracy_score(y_test, y_pred_af):.2f}")
print(classification_report(y_test, y_pred_af))
print("Matrice de confusion :\n", confusion_matrix(y_test, y_pred_af))

c:\Users\H P\git\projetTutore\venv\lib\site-packages\autofeat\featsel.py:270: FutureWarning: Series.ravel is deprecated. The underlying array is already 1D, so ravel is not necessary.  Use `to_numpy()` for conversion to a numpy array instead.
  if np.max(np.abs(correlations[c].ravel()[:i])) < 0.9:
c:\Users\H P\git\projetTutore\venv\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Nombre de nouvelles features créées : 13

 Performance APRÈS AutoFeat
Précision : 0.77
              precision    recall  f1-score   support

           0       0.69      0.37      0.48        59
           1       0.78      0.93      0.85       141

    accuracy                           0.77       200
   macro avg       0.73      0.65      0.67       200
weighted avg       0.75      0.77      0.74       200

Matrice de confusion :
 [[ 22  37]
 [ 10 131]]

In [ ]:
to install
python -m pip install jupyter-server-proxy
distributed

In [51]:
df["customer_id"] = range(1, len(df) + 1)
customers = df[["customer_id", "Age", "Sex", "Job", "Housing", "Saving accounts", "Checking account"]]
loans = df[["customer_id", "Credit amount", "Duration", "Purpose", "Risk"]]
loans.reset_index()

     index  customer_id  Credit amount  Duration  Purpose  Risk
0        0            1           1169         6        5     1
1        1            2           5951        48        5     0
2        2            3           2096        12        3     1
3        3            4           7882        42        4     1
4        4            5           4870        24        1     0
..     ...          ...            ...       ...      ...   ...
995    995          996           1736        12        4     1
996    996          997           3857        30        1     1
997    997          998            804        12        5     1
998    998          999           1845        45        5     0
999    999         1000           4576        45        1     1

[1000 rows x 6 columns]

In [48]:
loans.index()

TypeError: 'Index' object is not callable

In [52]:


entities={
    "customers":(customers,"customer_id"),
    "loans":(loans,"index",)
}
relationships=[("customers","customer_id","loans","customer_id")
    
]

feature_matrix_customers, features_defs = ft.dfs(dataframes=entities,
                                                 relationships=relationships,
                                                 target_dataframe_name="customers")

c:\Users\H P\git\projetTutoreAutoFE\venv\lib\site-packages\featuretools\entityset\entityset.py:1733: UserWarning: index index not found in dataframe, creating new integer column
  warnings.warn(
c:\Users\H P\git\projetTutoreAutoFE\venv\lib\site-packages\featuretools\computational_backends\feature_set_calculator.py:785: FutureWarning: The provided callable <function std at 0x000001EBF2E971C0> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  ).agg(to_agg)
c:\Users\H P\git\projetTutoreAutoFE\venv\lib\site-packages\featuretools\computational_backends\feature_set_calculator.py:785: FutureWarning: The provided callable <function mean at 0x000001EBF2E970A0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  ).agg(to_agg)
c:\Users\H P\git\projetTutoreAutoFE\venv\lib\site-packages\featuretools\computational_backends\feature_set_calculator.py:785: FutureWarning: The provided callable <function sum at 0x000001EBF2E96170> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  ).agg(to_agg)
c:\Users\H P\git\projetTutoreAutoFE\venv\lib\site-packages\featuretools\computational_backends\feature_set_calculator.py:785: FutureWarning: The provided callable <function min at 0x000001EBF2E968C0> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  ).agg(to_agg)
c:\Users\H P\git\projetTutoreAutoFE\venv\lib\site-packages\featuretools\computational_backends\feature_set_calculator.py:785: FutureWarning: The provided callable <function max at 0x000001EBF2E967A0> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  ).agg(to_agg)

In [53]:
feature_matrix_customers

,Age,Sex,Job,Housing,Saving accounts,Checking account,COUNT(loans),MAX(loans.Credit amount),MAX(loans.Duration),MAX(loans.Purpose),...,SKEW(loans.Purpose),SKEW(loans.Risk),STD(loans.Credit amount),STD(loans.Duration),STD(loans.Purpose),STD(loans.Risk),SUM(loans.Credit amount),SUM(loans.Duration),SUM(loans.Purpose),SUM(loans.Risk)
customer_id,,,,,,,,,,,,,,,,,,,,,
1,67,1,2,1,4,0,1,1169.0,6.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1169.0,6.0,5.0,1.0
2,22,0,2,1,0,1,1,5951.0,48.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,5951.0,48.0,5.0,0.0
3,49,1,1,1,0,3,1,2096.0,12.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2096.0,12.0,3.0,1.0
4,45,1,2,0,0,0,1,7882.0,42.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,7882.0,42.0,4.0,1.0
5,53,1,2,0,0,0,1,4870.0,24.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4870.0,24.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,31,0,1,1,0,3,1,1736.0,12.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1736.0,12.0,4.0,1.0
997,40,1,3,1,0,0,1,3857.0,30.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3857.0,30.0,1.0,1.0
998,38,1,2,1,0,3,1,804.0,12.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,804.0,12.0,5.0,1.0
999,23,1,2,0,0,0,1,1845.0,45.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1845.0,45.0,5.0,0.0
1000,27,1,2,1,1,1,1,4576.0,45.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4576.0,45.0,1.0,1.0

In [28]:
es = ft.EntitySet(id="credit_risk")

In [30]:
es = es.add_dataframe(dataframe_name="customers", dataframe=customers, index="customer_id")
es = es.add_dataframe(dataframe_name="loans", dataframe=loans,make_index = True, index="custo_loan_id")

c:\Users\H P\git\projetTutoreAutoFE\venv\lib\site-packages\featuretools\entityset\entityset.py:724: UserWarning: A Woodwork-initialized DataFrame was provided, so the following parameters were ignored: index
  warnings.warn(

In [31]:
es = es.add_relationship("customers","customer_id","loans","customer_id")

In [32]:
print(es)

Entityset: credit_risk
  DataFrames:
    customers [Rows: 1000, Columns: 7]
    loans [Rows: 1000, Columns: 6]
  Relationships:
    loans.customer_id -> customers.customer_id

In [33]:
agg_primitives =  ["sum", "std", "max", "skew", "min", "mean", "count", "percent_true", "num_unique", "mode"]
trans_primitives =  ["day", "year", "month", "weekday", "haversine", 
"num_words", "num_characters"]

In [38]:
print(trans_primitives)
print(agg_primitives)

['day', 'year', 'month', 'weekday', 'haversine', 'num_words', 'num_characters']
['sum', 'std', 'max', 'skew', 'min', 'mean', 'count', 'percent_true', 'num_unique', 'mode']

In [39]:
feature_matrix, feature_defs = ft.dfs(entityset = es, 
target_dataframe_name = 'loans',
    trans_primitives = trans_primitives,
    agg_primitives=agg_primitives,
    max_depth = 2, n_jobs = -1, verbose = 1)

c:\Users\H P\git\projetTutoreAutoFE\venv\lib\site-packages\featuretools\synthesis\dfs.py:321: UnusedPrimitiveWarning: Some specified primitives were not used during DFS:
  trans_primitives: ['day', 'haversine', 'month', 'num_characters', 'num_words', 'weekday', 'year']
  agg_primitives: ['mode', 'num_unique', 'percent_true']
This may be caused by a using a value of max_depth that is too small, not setting interesting values, or it may indicate no compatible columns for the primitive were found in the data. If the DFS call contained multiple instances of a primitive in the list above, none of them were used.
  warnings.warn(warning_msg, UnusedPrimitiveWarning)

Built 36 features
Elapsed: 00:00 | Progress:   0%|

2025-03-25 11:18:04,923 INFO: State start
2025-03-25 11:18:04,955 INFO:   Scheduler at:     tcp://127.0.0.1:63003
2025-03-25 11:18:04,955 INFO:   dashboard at:  http://127.0.0.1:8787/status
2025-03-25 11:18:04,955 INFO: Registering Worker plugin shuffle
2025-03-25 11:18:05,156 INFO:         Start Nanny at: 'tcp://127.0.0.1:63008'
2025-03-25 11:18:05,156 INFO:         Start Nanny at: 'tcp://127.0.0.1:63012'
2025-03-25 11:18:05,156 INFO:         Start Nanny at: 'tcp://127.0.0.1:63014'
2025-03-25 11:18:05,178 INFO:         Start Nanny at: 'tcp://127.0.0.1:63013'
2025-03-25 11:18:05,192 INFO:         Start Nanny at: 'tcp://127.0.0.1:63006'
2025-03-25 11:18:05,206 INFO:         Start Nanny at: 'tcp://127.0.0.1:63017'
2025-03-25 11:18:05,227 INFO:         Start Nanny at: 'tcp://127.0.0.1:63010'
2025-03-25 11:18:05,240 INFO:         Start Nanny at: 'tcp://127.0.0.1:63009'
2025-03-25 11:18:05,261 INFO:         Start Nanny at: 'tcp://127.0.0.1:63011'
2025-03-25 11:18:05,276 INFO:         Start Nanny at: 'tcp://127.0.0.1:63016'
2025-03-25 11:18:05,305 INFO:         Start Nanny at: 'tcp://127.0.0.1:63015'
2025-03-25 11:18:05,314 INFO:         Start Nanny at: 'tcp://127.0.0.1:63007'
2025-03-25 11:18:09,306 INFO: Register worker addr: tcp://127.0.0.1:63054 name: 8
2025-03-25 11:18:09,306 INFO: Starting worker compute stream, tcp://127.0.0.1:63054
2025-03-25 11:18:09,314 INFO: Starting established connection to tcp://127.0.0.1:63060
2025-03-25 11:18:09,322 INFO: Register worker addr: tcp://127.0.0.1:63056 name: 7
2025-03-25 11:18:09,330 INFO: Starting worker compute stream, tcp://127.0.0.1:63056
2025-03-25 11:18:09,330 INFO: Starting established connection to tcp://127.0.0.1:63067
2025-03-25 11:18:09,330 INFO: Register worker addr: tcp://127.0.0.1:63055 name: 2
2025-03-25 11:18:09,345 INFO: Starting worker compute stream, tcp://127.0.0.1:63055
2025-03-25 11:18:09,349 INFO: Starting established connection to tcp://127.0.0.1:63062
2025-03-25 11:18:09,349 INFO: Register worker addr: tcp://127.0.0.1:63057 name: 6
2025-03-25 11:18:09,357 INFO: Starting worker compute stream, tcp://127.0.0.1:63057
2025-03-25 11:18:09,365 INFO: Starting established connection to tcp://127.0.0.1:63066
2025-03-25 11:18:09,376 INFO: Register worker addr: tcp://127.0.0.1:63059 name: 1
2025-03-25 11:18:09,390 INFO: Starting worker compute stream, tcp://127.0.0.1:63059
2025-03-25 11:18:09,390 INFO: Starting established connection to tcp://127.0.0.1:63070
2025-03-25 11:18:09,450 INFO: Register worker addr: tcp://127.0.0.1:63063 name: 5
2025-03-25 11:18:09,457 INFO: Starting worker compute stream, tcp://127.0.0.1:63063
2025-03-25 11:18:09,457 INFO: Starting established connection to tcp://127.0.0.1:63072
2025-03-25 11:18:09,629 INFO: Register worker addr: tcp://127.0.0.1:63069 name: 3
2025-03-25 11:18:09,637 INFO: Starting worker compute stream, tcp://127.0.0.1:63069
2025-03-25 11:18:09,637 INFO: Starting established connection to tcp://127.0.0.1:63076
2025-03-25 11:18:09,701 INFO: Register worker addr: tcp://127.0.0.1:63073 name: 0
2025-03-25 11:18:09,710 INFO: Starting worker compute stream, tcp://127.0.0.1:63073
2025-03-25 11:18:09,710 INFO: Starting established connection to tcp://127.0.0.1:63079
2025-03-25 11:18:09,718 INFO: Register worker addr: tcp://127.0.0.1:63074 name: 4
2025-03-25 11:18:09,725 INFO: Starting worker compute stream, tcp://127.0.0.1:63074
2025-03-25 11:18:09,725 INFO: Starting established connection to tcp://127.0.0.1:63082
2025-03-25 11:18:09,791 INFO: Register worker addr: tcp://127.0.0.1:63080 name: 9
2025-03-25 11:18:09,791 INFO: Starting worker compute stream, tcp://127.0.0.1:63080
2025-03-25 11:18:09,791 INFO: Starting established connection to tcp://127.0.0.1:63086
2025-03-25 11:18:09,799 INFO: Register worker addr: tcp://127.0.0.1:63078 name: 10
2025-03-25 11:18:09,807 INFO: Starting worker compute stream, tcp://127.0.0.1:63078
2025-03-25 11:18:09,807 INFO: Starting established connection to tcp://127.0.0.1:63084
2025-03-25 11:18:09,912 INFO: Register worker addr: tcp://127.0.0.1:63087 name: 11
2025-03-25 11:18:09,917 INFO: Starting worker compute stream, tcp://127.0.0.1:63087
2025-03-25 11:18:09,917 INFO: Starting established connection to tcp://127.0.0.1:63089
2025-03-25 11:18:09,985 INFO: Receive client connection: Client-739e7521-0962-11f0-b024-30f6ef24d8b1
2025-03-25 11:18:09,993 INFO: Starting established connection to tcp://127.0.0.1:63093
2025-03-25 11:18:21,652 INFO: Remove client Client-739e7521-0962-11f0-b024-30f6ef24d8b1
2025-03-25 11:18:21,652 INFO: Received 'close-stream' from tcp://127.0.0.1:63093; closing.
2025-03-25 11:18:21,663 INFO: Remove client Client-739e7521-0962-11f0-b024-30f6ef24d8b1
2025-03-25 11:18:21,679 INFO: Batched Comm Closed <TCP (closed) Scheduler->Client local=tcp://127.0.0.1:63003 remote=tcp://127.0.0.1:63093>
Traceback (most recent call last):
  File "c:\Users\H P\git\projetTutoreAutoFE\venv\lib\site-packages\distributed\batched.py", line 115, in _background_send
    nbytes = yield coro
  File "c:\Users\H P\git\projetTutoreAutoFE\venv\lib\site-packages\tornado\gen.py", line 766, in run
    value = future.result()
  File "c:\Users\H P\git\projetTutoreAutoFE\venv\lib\site-packages\distributed\comm\tcp.py", line 263, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
2025-03-25 11:18:21,684 INFO: Close client connection: Client-739e7521-0962-11f0-b024-30f6ef24d8b1
2025-03-25 11:18:21,689 INFO: Retire worker addresses (stimulus_id='retire-workers-1742897907.5278552') (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)
2025-03-25 11:18:21,692 INFO: Closing Nanny at 'tcp://127.0.0.1:63006'. Reason: nanny-close
2025-03-25 11:18:21,694 INFO: Nanny asking worker to close. Reason: nanny-close
2025-03-25 11:18:21,696 INFO: Closing Nanny at 'tcp://127.0.0.1:63007'. Reason: nanny-close
2025-03-25 11:18:21,703 INFO: Nanny asking worker to close. Reason: nanny-close
2025-03-25 11:18:21,710 INFO: Closing Nanny at 'tcp://127.0.0.1:63008'. Reason: nanny-close
2025-03-25 11:18:21,715 INFO: Nanny asking worker to close. Reason: nanny-close
2025-03-25 11:18:21,717 INFO: Closing Nanny at 'tcp://127.0.0.1:63009'. Reason: nanny-close
2025-03-25 11:18:21,719 INFO: Nanny asking worker to close. Reason: nanny-close
2025-03-25 11:18:21,726 INFO: Closing Nanny at 'tcp://127.0.0.1:63010'. Reason: nanny-close
2025-03-25 11:18:21,728 INFO: Nanny asking worker to close. Reason: nanny-close
2025-03-25 11:18:21,741 INFO: Closing Nanny at 'tcp://127.0.0.1:63011'. Reason: nanny-close
2025-03-25 11:18:21,747 INFO: Nanny asking worker to close. Reason: nanny-close
2025-03-25 11:18:21,751 INFO: Closing Nanny at 'tcp://127.0.0.1:63012'. Reason: nanny-close
2025-03-25 11:18:21,760 INFO: Nanny asking worker to close. Reason: nanny-close
2025-03-25 11:18:21,767 INFO: Closing Nanny at 'tcp://127.0.0.1:63013'. Reason: nanny-close
2025-03-25 11:18:21,779 INFO: Nanny asking worker to close. Reason: nanny-close
2025-03-25 11:18:21,787 INFO: Closing Nanny at 'tcp://127.0.0.1:63014'. Reason: nanny-close
2025-03-25 11:18:21,795 INFO: Nanny asking worker to close. Reason: nanny-close
2025-03-25 11:18:21,803 INFO: Closing Nanny at 'tcp://127.0.0.1:63015'. Reason: nanny-close
2025-03-25 11:18:21,821 INFO: Nanny asking worker to close. Reason: nanny-close
2025-03-25 11:18:21,830 INFO: Closing Nanny at 'tcp://127.0.0.1:63016'. Reason: nanny-close
2025-03-25 11:18:21,843 INFO: Nanny asking worker to close. Reason: nanny-close
2025-03-25 11:18:21,847 INFO: Closing Nanny at 'tcp://127.0.0.1:63017'. Reason: nanny-close
2025-03-25 11:18:21,858 INFO: Nanny asking worker to close. Reason: nanny-close
2025-03-25 11:18:22,446 INFO: Received 'close-stream' from tcp://127.0.0.1:63062; closing.
2025-03-25 11:18:22,463 INFO: Received 'close-stream' from tcp://127.0.0.1:63066; closing.
2025-03-25 11:18:22,463 INFO: Received 'close-stream' from tcp://127.0.0.1:63082; closing.
2025-03-25 11:18:22,463 INFO: Received 'close-stream' from tcp://127.0.0.1:63070; closing.
2025-03-25 11:18:22,463 INFO: Received 'close-stream' from tcp://127.0.0.1:63067; closing.
2025-03-25 11:18:22,475 INFO: Received 'close-stream' from tcp://127.0.0.1:63079; closing.
2025-03-25 11:18:22,479 INFO: Received 'close-stream' from tcp://127.0.0.1:63076; closing.
2025-03-25 11:18:22,483 INFO: Received 'close-stream' from tcp://127.0.0.1:63072; closing.
2025-03-25 11:18:22,589 INFO: Remove worker addr: tcp://127.0.0.1:63055 name: 2 (stimulus_id='handle-worker-cleanup-1742897908.428194')
2025-03-25 11:18:22,594 INFO: Remove worker addr: tcp://127.0.0.1:63057 name: 6 (stimulus_id='handle-worker-cleanup-1742897908.431966')
2025-03-25 11:18:22,594 INFO: Remove worker addr: tcp://127.0.0.1:63074 name: 4 (stimulus_id='handle-worker-cleanup-1742897908.4371316')
2025-03-25 11:18:22,601 INFO: Remove worker addr: tcp://127.0.0.1:63059 name: 1 (stimulus_id='handle-worker-cleanup-1742897908.4427557')
2025-03-25 11:18:22,607 INFO: Remove worker addr: tcp://127.0.0.1:63056 name: 7 (stimulus_id='handle-worker-cleanup-1742897908.4467223')
2025-03-25 11:18:22,611 INFO: Remove worker addr: tcp://127.0.0.1:63073 name: 0 (stimulus_id='handle-worker-cleanup-1742897908.4522448')
2025-03-25 11:18:22,622 INFO: Remove worker addr: tcp://127.0.0.1:63069 name: 3 (stimulus_id='handle-worker-cleanup-1742897908.4606838')
2025-03-25 11:18:22,622 INFO: Remove worker addr: tcp://127.0.0.1:63063 name: 5 (stimulus_id='handle-worker-cleanup-1742897908.4647188')
2025-03-25 11:18:22,628 INFO: Received 'close-stream' from tcp://127.0.0.1:63084; closing.
2025-03-25 11:18:22,633 INFO: Received 'close-stream' from tcp://127.0.0.1:63089; closing.
2025-03-25 11:18:23,034 INFO: Remove worker addr: tcp://127.0.0.1:63078 name: 10 (stimulus_id='handle-worker-cleanup-1742897908.8742566')
2025-03-25 11:18:23,034 INFO: Remove worker addr: tcp://127.0.0.1:63087 name: 11 (stimulus_id='handle-worker-cleanup-1742897908.8772373')
2025-03-25 11:18:23,034 INFO: Received 'close-stream' from tcp://127.0.0.1:63060; closing.
2025-03-25 11:18:23,034 INFO: Received 'close-stream' from tcp://127.0.0.1:63086; closing.
2025-03-25 11:18:23,045 INFO: Remove worker addr: tcp://127.0.0.1:63054 name: 8 (stimulus_id='handle-worker-cleanup-1742897908.8885877')
2025-03-25 11:18:23,045 INFO: Remove worker addr: tcp://127.0.0.1:63080 name: 9 (stimulus_id='handle-worker-cleanup-1742897908.8904297')
2025-03-25 11:18:23,045 ERROR: Removing worker 'tcp://127.0.0.1:63080' caused the cluster to lose scattered data, which can't be recovered: {'EntitySet-23505087cc61d94c7859e112cd5b347a'} (stimulus_id='handle-worker-cleanup-1742897908.8904297')
2025-03-25 11:18:23,045 INFO: Lost all workers
2025-03-25 11:18:23,112 INFO: Nanny at 'tcp://127.0.0.1:63006' closed.
2025-03-25 11:18:23,112 INFO: Nanny at 'tcp://127.0.0.1:63008' closed.
2025-03-25 11:18:23,112 INFO: Nanny at 'tcp://127.0.0.1:63013' closed.
2025-03-25 11:18:23,112 INFO: Nanny at 'tcp://127.0.0.1:63009' closed.
2025-03-25 11:18:23,112 INFO: Nanny at 'tcp://127.0.0.1:63012' closed.
2025-03-25 11:18:23,112 INFO: Nanny at 'tcp://127.0.0.1:63016' closed.
2025-03-25 11:18:23,126 INFO: Nanny at 'tcp://127.0.0.1:63014' closed.
2025-03-25 11:18:23,128 INFO: Nanny at 'tcp://127.0.0.1:63007' closed.
2025-03-25 11:18:23,128 INFO: Nanny at 'tcp://127.0.0.1:63010' closed.
2025-03-25 11:18:23,128 INFO: Nanny at 'tcp://127.0.0.1:63017' closed.
2025-03-25 11:18:23,128 INFO: Nanny at 'tcp://127.0.0.1:63011' closed.
2025-03-25 11:18:23,134 INFO: Nanny at 'tcp://127.0.0.1:63015' closed.
2025-03-25 11:18:23,140 INFO: Closing scheduler. Reason: unknown
2025-03-25 11:18:23,141 INFO: Scheduler closing all comms

Elapsed: 00:18 | Progress:   0%|

AttributeError: 'NoneType' object has no attribute 'status'

In [ ]:
#https://www.analyticsvidhya.com/blog/2018/08/guide-automated-feature-engineering-featuretools-python/
#https://ranasinghiitkgp.medium.com/feature-engineering-using-featuretools-with-code-10f8c83e5f68
#Avec featuretools

df_ft = df.reset_index().rename(columns={'index': 'id'})
es = ft.EntitySet(id="dataset")

es = es.add_dataframe(
    dataframe_name="df_ft",  
    dataframe=df_ft,
    index="id"  
)

#création d'une entité (table) job
es.normalize_entity(
    base_dataframe_name="df_ft",
    new_dataframe_name="job_table",
    index="Job"
)

es.normalize_entity(
    base_dataframe_name="df_ft",
    new_dataframe_name="housing_table",
    index="Housing"
)

es.normalize_entity(
    base_dataframe_name="df_ft",
    new_dataframe_name="purpose_table",
    index="Purpose"
)

feature_matrix, feature_names = ft.dfs(
    entityset=es, 
    target_entity ="df_ft",  
    max_depth=4,
    
)

print(f"Nombre de nouvelles features créées : {feature_matrix.shape[1] - X.shape[1]}")

Nombre de nouvelles features créées : 1

c:\Users\H P\git\projetTutore\venv\lib\site-packages\featuretools\synthesis\deep_feature_synthesis.py:169: UserWarning: Only one dataframe in entityset, changing max_depth to 1 since deeper features cannot be created
  warnings.warn(

In [22]:
print(es)

Entityset: dataset
  DataFrames:
    df_ft [Rows: 1000, Columns: 11]
  Relationships:
    No relationships

In [ ]:
X_train_ft, X_test_ft, y_train_ft, y_test_ft = train_test_split(feature_matrix, y, test_size=0.2, random_state=42)
model = LogisticRegression()
model.fit(X_train_ft, y_train_ft)
y_pred_ft = model.predict(X_test_ft)

print("\n Performance APRÈS AutoFeat")
print(f"Précision : {accuracy_score(y_test_ft, y_pred_ft):.2f}")
print(classification_report(y_test_ft, y_pred_ft))
print("Matrice de confusion :\n", confusion_matrix(y_test_ft, y_pred_ft))